config/routes.rb
Crocusfields::Application.routes.draw do
 resources :users do
      member do
          get :following, :followers
      end
  end

  resources :password_resets

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :messages do
      get :autocomplete_user_name, :on => :collection
  end

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/inbox', to: 'messages#show'
  match '/sent', to: 'messages#index'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

  get 'user/autocomplete_user_name'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_autocomplete.html.erb
<div id="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <%= content_tag :h1, yield(:title) if show_title? %>
  <%= yield %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  Similarity breeds content.
  <nav>
    <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <nav>
                <ul class="nav pull-right">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Help", help_path %></li>
                    <% if signed_in? %>
                        <li><%= link_to "Users", users_path %></li>
                       <li id="fat-menu" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Mailbox <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Inbox", inbox_path %></li>
                                <li><%= link_to "Sent", sent_path %></li>
                                <li><%= link_to "Compose", new_message_path %></li>
                            </ul>
                        </li>
                         <li id="fat-menu" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Account <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Profile", current_user %></li>
                                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                <li class="divider"></li>
                                <li>
                                    <%= link_to "Sign out", signout_path, method: "delete" %>
                                </li>
                            </ul>
                        </li>
                        <% else %>
                            <li><%= link_to "Sign in", signin_path %></li>
                        <% end %>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag "application", media: "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
        <link href='http://fonts.googleapis.com/css?family=Enriqueta' rel="stylesheet" type="text/css">

    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |key, value| %>
                <%= content_tag(:div, value, class: "alert alert-#{key}") %>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %> 
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>